name: osama_shop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  iso_countries: ^2.1.0
  scrollable_positioned_list: ^0.2.3
  country_codes: ^2.1.1
  intl: ^0.17.0
  provider: ^6.0.2
  google_fonts: ^2.2.0
  flutter_signin_button: ^2.0.0
  page_transition: ^2.0.4
  custom_refresh_indicator: ^1.0.0
  flutter_facebook_auth: ^4.0.1
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth_platform_interface: ^6.1.10
  fluttertoast: ^8.0.8
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/first-time.png
    - assets/images/google.png